# 简化的 Nginx Proxy HTTPS 配置
# 包含所有服务：nginx-proxy + letsencrypt + 多个应用服务

services:
  # Nginx 反向代理
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/certs
      - /etc/nginx/vhost.d
      - acme:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro

  # Let's Encrypt 证书管理
  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-le
    restart: always
    depends_on:
      - nginx-proxy
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy 
      - DEFAULT_EMAIL=${DEFAULT_EMAIL}
      - DEFAULT_RENEW=${DEFAULT_RENEW:-30}
      - CERTS_UPDATE_INTERVAL=${CERTS_UPDATE_INTERVAL:-3600}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - /etc/nginx/vhost.d
      - acme:/usr/share/nginx/html

  # 服务2: 前端应用 (使用80端口)
  frontend-app:
    container_name: frontend_app
    restart: always
    image: nginx:alpine
    expose:
      - "80"  # nginx默认监听80端口
    environment:
      - VIRTUAL_HOST=app.your-domain.com
      - VIRTUAL_PORT=80  # 告诉nginx-proxy转发到80端口
      - LETSENCRYPT_HOST=app.your-domain.com
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}

  # 服务3: 管理后台 (使用80端口)
  admin-panel:
    container_name: admin_panel
    restart: always
    image: nginx:alpine
    expose:
      - "80"  # nginx默认监听80端口
    environment:
      - VIRTUAL_HOST=monitor.your-domain.com
      - VIRTUAL_PORT=80  # 告诉nginx-proxy转发到80端口
      - LETSENCRYPT_HOST=monitor.your-domain.com
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}

  # 服务4: 监控服务 (使用80端口)
  monitoring:
    container_name: monitoring_service
    restart: always
    image: nginx:alpine
    expose:
      - "80"  # nginx默认监听80端口
    environment:
      - VIRTUAL_HOST=monitor.your-domain.com
      - VIRTUAL_PORT=80  # 告诉nginx-proxy转发到80端口
      - LETSENCRYPT_HOST=monitor.your-domain.com
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}

volumes:
  acme:


